Topic.create(:name => "Keyboards")
Topic.create(:name => "Violin")
Topic.create(:name => "Geometry")
Topic.create(:name => "Painting")
Topic.create(:name => "Cooking")
Topic.create(:name => "Yoga")
Topic.create(:name => "Creative Writing")
